version: '3.4'

services:
  samurai_postgres:
    image: postgres
    
    command: postgres -c full_page_writes=off -c shared_preload_libraries='pg_stat_statements'
    container_name: samurai_postgres
    environment: 
        POSTGRES_PASSWORD: 12qwasZX
        PGDATA: pgdata
    ports: 
        - "5433:5432"  
       
