version: '3.4'

services:

    samurai.api:
      image: docker.linker.by/samurai.api
      container_name: samurai.api
      network_mode: host
      environment: 
        - ASPNETCORE_URLS=http://0.0.0.0:5000/
      volumes: 
        - ./appsettings.json:/app/appsettings.json
      depends_on: 
        - samurai_postgres

    samurai_postgres:
      image: postgres
      command: postgres -c full_page_writes=off -c shared_preload_libraries='pg_stat_statements'
      container_name: samurai_postgres
      environment: 
          POSTGRES_PASSWORD: 12qwasZX
          PGDATA: pgdata
      ports: 
          - "5433:5432"  